// =============================================
// Post Topic Library — curated for the
// "AI Automation Architect + Full-Stack" niche.
// 50+ topics per category, plus trending 2026 picks.
// =============================================

import type { LinkedInPost } from './types';

export interface TopicSuggestion {
  id: string;
  topic: string;
  postType: LinkedInPost['postType'];
  category: string;
  emoji: string;
  trending?: boolean;
}

export const TOPIC_CATEGORIES = [
  { id: 'all', label: 'All', emoji: '✨' },
  { id: 'trending', label: 'Trending', emoji: '🔥' },
  { id: 'ai-automation', label: 'AI & n8n', emoji: '🤖' },
  { id: 'llms', label: 'LLMs & ML', emoji: '🧠' },
  { id: 'dev-lessons', label: 'Dev', emoji: '⚙️' },
  { id: 'freelance', label: 'Freelance', emoji: '💼' },
  { id: 'hot-takes', label: 'Hot Takes', emoji: '🌶️' },
  { id: 'case-studies', label: 'Cases', emoji: '📊' },
];

// Short ID helper
let _id = 0;
const mk = (
  topic: string,
  postType: LinkedInPost['postType'],
  category: string,
  emoji: string,
  trending = false,
): TopicSuggestion => ({
  id: `topic-${++_id}`,
  topic,
  postType,
  category,
  emoji,
  trending,
});

// =============================================
// AI Automation / n8n (50)
// =============================================
const AI_AUTOMATION: TopicSuggestion[] = [
  mk('Why I replaced Zapier with n8n and saved a client $4K/year', 'case-study', 'ai-automation', '💰', true),
  mk('5 n8n workflows every startup should build in their first month', 'tips', 'ai-automation', '⚡'),
  mk('I automated lead qualification — my client got back 10 hours/week', 'case-study', 'ai-automation', '⏱️'),
  mk('n8n vs Make vs Zapier — which one to pick in 2026 and why', 'thought-leadership', 'ai-automation', '🤔', true),
  mk('The n8n AI nodes nobody talks about — but they\'re game-changing', 'tips', 'ai-automation', '🪄'),
  mk('How I built an autonomous sales outreach agent with n8n + OpenAI', 'case-study', 'ai-automation', '🚀', true),
  mk('The automation audit I run on every new client (free template)', 'tips', 'ai-automation', '🔍'),
  mk('Why low-code beats no-code for complex AI workflows', 'thought-leadership', 'ai-automation', '⚙️'),
  mk('n8n self-hosting vs cloud — my real cost comparison after 1 year', 'case-study', 'ai-automation', '💵'),
  mk('How to build an email triage agent in n8n (with pricing breakdown)', 'tips', 'ai-automation', '📧'),
  mk('3 AI automations that pay for themselves in 30 days', 'tips', 'ai-automation', '💸'),
  mk('The hidden cost of Zapier at scale (and what I switched to)', 'story', 'ai-automation', '💼', true),
  mk('Why your "AI strategy" fails without workflow automation', 'thought-leadership', 'ai-automation', '🎯'),
  mk('Build vs buy: when to use n8n vs building from scratch', 'thought-leadership', 'ai-automation', '⚖️'),
  mk('The 5 most common n8n mistakes I see freelancers make', 'tips', 'ai-automation', '⚠️'),
  mk('How I automated client onboarding and cut it from 3 days to 1 hour', 'case-study', 'ai-automation', '✅'),
  mk('Building AI customer support agents: architecture breakdown', 'case-study', 'ai-automation', '🎧'),
  mk('Why I stopped using "if-this-then-that" and embraced AI agents', 'story', 'ai-automation', '🤖'),
  mk('n8n + Airtable + GPT: the stack that replaces entire SaaS tools', 'thought-leadership', 'ai-automation', '🧱', true),
  mk('How to monitor and debug production n8n workflows properly', 'tips', 'ai-automation', '📊'),
  mk('The automation roadmap I follow with every new client', 'tips', 'ai-automation', '🗺️'),
  mk('Webhooks, queues, and retries: making n8n production-grade', 'tips', 'ai-automation', '🔁'),
  mk('The $500 n8n workflow I build for every agency client', 'case-study', 'ai-automation', '💎'),
  mk('Why "prompt chaining" changed how I design automations', 'thought-leadership', 'ai-automation', '🔗'),
  mk('Building a lead scoring AI in n8n — complete walkthrough', 'case-study', 'ai-automation', '🎯'),
  mk('n8n error handling patterns that saved my client from a $10K bug', 'story', 'ai-automation', '🐛'),
  mk('How I charge for AI automation projects (my exact pricing)', 'tips', 'ai-automation', '💲'),
  mk('From demo to production: the n8n checklist I use every time', 'tips', 'ai-automation', '✔️'),
  mk('Why most "AI agents" are just disguised n8n workflows', 'engagement', 'ai-automation', '🎭', true),
  mk('Automate your Notion with n8n — 5 workflows every team needs', 'tips', 'ai-automation', '📝'),
  mk('The data pipeline I built for an e-commerce brand in 3 days', 'case-study', 'ai-automation', '📦'),
  mk('Multi-step AI workflows vs single giant prompts — when to use each', 'thought-leadership', 'ai-automation', '🪜'),
  mk('I connected 12 SaaS tools with n8n. Here\'s what broke first.', 'story', 'ai-automation', '🔌'),
  mk('Why the n8n "self-hosted" argument is usually wrong', 'engagement', 'ai-automation', '🏠'),
  mk('How to sell n8n automations to clients who\'ve never heard of it', 'tips', 'ai-automation', '🗣️'),
  mk('The 4-stage AI workflow template that works for 80% of clients', 'tips', 'ai-automation', '📐'),
  mk('How I make $3K/month from a single n8n workflow I built in 2022', 'story', 'ai-automation', '📈'),
  mk('n8n for solopreneurs: the 10 workflows I run daily', 'tips', 'ai-automation', '🧑‍💻'),
  mk('When to use n8n, when to use Temporal, when to use raw code', 'thought-leadership', 'ai-automation', '🎛️'),
  mk('Why observability is the #1 skill for AI automation engineers', 'thought-leadership', 'ai-automation', '👁️'),
  mk('A founder asked me to "just add AI" — here\'s what I actually built', 'story', 'ai-automation', '🛠️', true),
  mk('The Slack bot I built in 30 minutes that replaced a full-time role', 'case-study', 'ai-automation', '🤖'),
  mk('Make.com to n8n migration: my 3-step process', 'tips', 'ai-automation', '🔄'),
  mk('The automation consulting framework I use to scope projects', 'tips', 'ai-automation', '📋'),
  mk('Why I include analytics dashboards with every n8n build', 'thought-leadership', 'ai-automation', '📊'),
  mk('Vector DBs + n8n: building searchable company knowledge bases', 'case-study', 'ai-automation', '🧭'),
  mk('Automation-first vs automation-later: which is better for your stack?', 'thought-leadership', 'ai-automation', '⏳'),
  mk('How to sell "boring automation" and make it exciting for buyers', 'tips', 'ai-automation', '✨'),
  mk('The day my n8n workflow went down and cost a client 400 leads', 'story', 'ai-automation', '😰'),
  mk('Why n8n is the Figma moment for backend development', 'engagement', 'ai-automation', '🎨', true),
];

// =============================================
// LLMs & ML (50)
// =============================================
const LLMS: TopicSuggestion[] = [
  mk('Context engineering > prompt engineering. Here\'s why.', 'thought-leadership', 'llms', '🎯', true),
  mk('RAG beats fine-tuning 90% of the time — and it\'s 10x cheaper', 'thought-leadership', 'llms', '📚', true),
  mk('3 mistakes I see every team make when shipping LLMs to production', 'tips', 'llms', '⚠️'),
  mk('How I design ML workflows that scale — a breakdown', 'case-study', 'llms', '🔧'),
  mk('When to use open-source LLMs vs GPT-4/Claude — a decision framework', 'thought-leadership', 'llms', '⚖️'),
  mk('Why most RAG implementations fail silently (and how to audit yours)', 'tips', 'llms', '🔍', true),
  mk('The embedding strategy that cut my client\'s retrieval costs by 60%', 'case-study', 'llms', '💰'),
  mk('Stop fine-tuning. 99% of you don\'t need to.', 'engagement', 'llms', '🛑', true),
  mk('My go-to LLM evaluation framework for client projects', 'tips', 'llms', '📏'),
  mk('Chunking strategies for RAG: what actually works in production', 'tips', 'llms', '📄'),
  mk('Why hybrid search (BM25 + vectors) beats pure semantic search', 'thought-leadership', 'llms', '🔀'),
  mk('The LLM cost optimization playbook that saved my client $8K/month', 'case-study', 'llms', '💸'),
  mk('Structured outputs: the LLM feature that changed my entire workflow', 'thought-leadership', 'llms', '📋', true),
  mk('How to build an AI agent that doesn\'t hallucinate into production', 'tips', 'llms', '🚫'),
  mk('Claude vs GPT-4 vs Gemini: my honest take after 100 client projects', 'thought-leadership', 'llms', '🥊', true),
  mk('Prompt caching: the 90% cost reduction nobody\'s using', 'tips', 'llms', '💾', true),
  mk('Why small models win for 70% of production use cases', 'thought-leadership', 'llms', '🐣'),
  mk('Building your first LLM eval suite in under an hour', 'tips', 'llms', '🧪'),
  mk('My LLM observability stack (and why you need one)', 'tips', 'llms', '📡'),
  mk('The day ChatGPT changed a prompt and broke my client\'s app', 'story', 'llms', '😱'),
  mk('Function calling vs structured outputs — when to use each', 'tips', 'llms', '🔧'),
  mk('Multi-agent systems: hype vs what actually ships', 'thought-leadership', 'llms', '👥', true),
  mk('How I ship LLM features without blowing up API budgets', 'tips', 'llms', '💡'),
  mk('Semantic caching: the LLM optimization that pays for itself', 'thought-leadership', 'llms', '⚡'),
  mk('5 reasons your chatbot feels robotic (and how to fix them)', 'tips', 'llms', '🎭'),
  mk('From prototype to production: the LLM shipping checklist', 'tips', 'llms', '🚢'),
  mk('Why you should test LLM outputs with LLMs (yes, really)', 'thought-leadership', 'llms', '🪞'),
  mk('Retrieval-augmented generation: the 80/20 that works 80% of the time', 'thought-leadership', 'llms', '📖'),
  mk('Tool use: the LLM feature that makes agents actually useful', 'thought-leadership', 'llms', '🛠️'),
  mk('Streaming LLM responses: why it matters more than you think', 'tips', 'llms', '🌊'),
  mk('Building a semantic search engine: my complete architecture', 'case-study', 'llms', '🔎'),
  mk('Why "vibes-based" LLM testing doesn\'t survive production', 'engagement', 'llms', '🎲'),
  mk('OpenAI vs Anthropic vs open-source: my 2026 production recommendation', 'thought-leadership', 'llms', '🏆', true),
  mk('The prompt library I\'ve built over 2 years (and still use)', 'tips', 'llms', '📚'),
  mk('How I implement guardrails in customer-facing LLM products', 'tips', 'llms', '🛡️'),
  mk('The "agent loop" pattern that solved my tricky automation problems', 'case-study', 'llms', '🔁'),
  mk('Why embeddings are the most underrated AI primitive', 'thought-leadership', 'llms', '🔢'),
  mk('I tested 12 vector databases so you don\'t have to — here\'s the winner', 'case-study', 'llms', '🗃️'),
  mk('Building LLM memory that actually persists across sessions', 'tips', 'llms', '🧠'),
  mk('How to make your LLM product feel 10x smarter without a bigger model', 'tips', 'llms', '💎'),
  mk('The one ML ops practice that cut my client\'s inference costs in half', 'case-study', 'llms', '📉'),
  mk('Chain-of-thought vs ReAct vs plan-and-execute: picking your pattern', 'tips', 'llms', '🎭'),
  mk('When not to use LLMs — a sanity-check framework', 'thought-leadership', 'llms', '🛑'),
  mk('Evaluating LLM output quality without humans in the loop', 'tips', 'llms', '🤖'),
  mk('Why LangChain lost me (and what I use now)', 'story', 'llms', '🪦', true),
  mk('The 3 LLM features I use on every new project', 'tips', 'llms', '⭐'),
  mk('How to prevent prompt injection in your LLM-powered product', 'tips', 'llms', '🚧'),
  mk('Building AI products that work offline (yes, it\'s possible)', 'thought-leadership', 'llms', '📴'),
  mk('The ML workflow template I\'ve refined over 3 years', 'tips', 'llms', '🧪'),
  mk('Why I prefer typed SDKs over raw API calls for LLM integration', 'thought-leadership', 'llms', '🔒'),
];

// =============================================
// Dev Lessons (50)
// =============================================
const DEV: TopicSuggestion[] = [
  mk('The Next.js 14 patterns that actually matter in production', 'tips', 'dev-lessons', '⚛️', true),
  mk('Python for AI, Node.js for the API — why this stack wins', 'thought-leadership', 'dev-lessons', '🔗'),
  mk('I moved my client\'s 3 repos into a monorepo. Here\'s what broke.', 'story', 'dev-lessons', '📦'),
  mk('7 API design rules I follow on every freelance project', 'tips', 'dev-lessons', '🔌'),
  mk('The TypeScript config I ship on every project (with explanations)', 'tips', 'dev-lessons', '🔧'),
  mk('React Server Components: what they\'re actually good for', 'thought-leadership', 'dev-lessons', '🖥️'),
  mk('Why I migrated from Redux to Zustand and never looked back', 'story', 'dev-lessons', '🐻'),
  mk('The Git workflow my team uses that ended our merge conflict wars', 'tips', 'dev-lessons', '🌿'),
  mk('FastAPI + Pydantic: the Python backend stack I use for AI apps', 'tips', 'dev-lessons', '🐍'),
  mk('How I test LLM-powered features (without hitting the API in tests)', 'tips', 'dev-lessons', '🧪'),
  mk('Why I ditched Docker for local dev (and what I use instead)', 'story', 'dev-lessons', '🐳', true),
  mk('5 security bugs I\'ve caught in LLM-powered apps', 'tips', 'dev-lessons', '🔒'),
  mk('The PostgreSQL features every backend dev should know', 'tips', 'dev-lessons', '🐘'),
  mk('Why I stopped using ORMs for complex queries', 'thought-leadership', 'dev-lessons', '📊'),
  mk('Building real-time features without a WebSocket nightmare', 'tips', 'dev-lessons', '📡'),
  mk('The deployment setup I use for every side project', 'tips', 'dev-lessons', '🚀'),
  mk('Supabase vs Firebase vs Convex: honest take from 10 production apps', 'thought-leadership', 'dev-lessons', '🗄️', true),
  mk('Why event-driven architecture saved my client\'s Black Friday', 'case-study', 'dev-lessons', '⚡'),
  mk('The observability stack I set up on day one of every project', 'tips', 'dev-lessons', '👁️'),
  mk('Python vs TypeScript for AI-heavy backends — my honest take', 'thought-leadership', 'dev-lessons', '🥊'),
  mk('React Query patterns that eliminated 80% of my state management', 'tips', 'dev-lessons', '🔄'),
  mk('Why I pair Tailwind + shadcn on every project now', 'thought-leadership', 'dev-lessons', '🎨'),
  mk('The one SQL skill that separates senior devs from juniors', 'tips', 'dev-lessons', '💡'),
  mk('How I structure large Next.js apps without tears', 'tips', 'dev-lessons', '🏗️'),
  mk('API versioning strategies that survive multiple clients', 'tips', 'dev-lessons', '🔢'),
  mk('The 3 caching layers every production app needs', 'tips', 'dev-lessons', '💾'),
  mk('Why I stopped writing Redux boilerplate forever', 'story', 'dev-lessons', '😌'),
  mk('Async Python patterns every AI backend needs', 'tips', 'dev-lessons', '⚡'),
  mk('My React performance checklist that fixed a client\'s 8s load time', 'case-study', 'dev-lessons', '🏎️'),
  mk('The dependency strategy I use to avoid npm hell', 'tips', 'dev-lessons', '📦'),
  mk('When to pick Prisma, Drizzle, or raw SQL', 'thought-leadership', 'dev-lessons', '🎯'),
  mk('Why I write integration tests, not unit tests (for most client work)', 'thought-leadership', 'dev-lessons', '✅'),
  mk('Error handling patterns that save your logs from uselessness', 'tips', 'dev-lessons', '🚨'),
  mk('The auth stack I recommend for every new startup project', 'tips', 'dev-lessons', '🔐'),
  mk('CI/CD pipelines that take 3 minutes to set up and save weeks', 'tips', 'dev-lessons', '🔄'),
  mk('Why rate limiting belongs in your first commit, not your first bug', 'thought-leadership', 'dev-lessons', '🚧'),
  mk('The API logging strategy that makes debugging 10x faster', 'tips', 'dev-lessons', '📝'),
  mk('Edge functions: when they\'re magic, when they\'re a trap', 'thought-leadership', 'dev-lessons', '🌐'),
  mk('Why I read the framework source code before every migration', 'thought-leadership', 'dev-lessons', '📖'),
  mk('Database migrations that don\'t take down production', 'tips', 'dev-lessons', '🔧'),
  mk('The one webpack config trick that saved my team hours per week', 'tips', 'dev-lessons', '⚙️'),
  mk('How I audit inherited codebases (the exact checklist)', 'tips', 'dev-lessons', '🔍'),
  mk('Why I always add feature flags to every production feature', 'tips', 'dev-lessons', '🚩'),
  mk('The TypeScript types I wish I knew in my first year', 'tips', 'dev-lessons', '📘'),
  mk('Why my error messages target future-me, not present-me', 'thought-leadership', 'dev-lessons', '💬'),
  mk('From monolith to microservices — and back again (a story)', 'story', 'dev-lessons', '🔄'),
  mk('The 10-minute code review checklist I use on my own PRs', 'tips', 'dev-lessons', '👀'),
  mk('Testing async code: patterns that don\'t flake', 'tips', 'dev-lessons', '⚡'),
  mk('The backup & disaster recovery plan I set up for every client', 'tips', 'dev-lessons', '🛟'),
  mk('Why boring tech beats shiny tech in client projects', 'thought-leadership', 'dev-lessons', '😴'),
];

// =============================================
// Freelance / Business (50)
// =============================================
const FREELANCE: TopicSuggestion[] = [
  mk('How I landed my first $10K client with zero cold outreach', 'story', 'freelance', '💼', true),
  mk('Why I stopped charging hourly and doubled my income', 'story', 'freelance', '💵', true),
  mk('The one contract clause that ended my scope creep problem forever', 'tips', 'freelance', '📄'),
  mk('My remote work setup that 3x\'d my deep-work hours', 'tips', 'freelance', '🏠'),
  mk('After 3 years freelancing, here\'s why I\'ll never go back to agencies', 'story', 'freelance', '🚪'),
  mk('The 5-question discovery call script that closes 60% of my leads', 'tips', 'freelance', '📞', true),
  mk('How I raised my rates 40% without losing a single client', 'story', 'freelance', '📈'),
  mk('The freelance pricing framework that ended my imposter syndrome', 'thought-leadership', 'freelance', '💎'),
  mk('Why I fired my biggest client (and 10x\'d my business)', 'story', 'freelance', '🔥'),
  mk('My exact proposal template that wins 70% of pitches', 'tips', 'freelance', '📝'),
  mk('Value-based pricing vs project pricing: the math no one shows you', 'thought-leadership', 'freelance', '🧮'),
  mk('The freelance "no" framework: when to turn down good projects', 'tips', 'freelance', '🛑'),
  mk('How I find 5 new leads a week without cold outreach', 'tips', 'freelance', '🎣', true),
  mk('LinkedIn > Upwork for high-ticket freelance clients — here\'s why', 'thought-leadership', 'freelance', '🔗'),
  mk('The payment terms I use to avoid ever chasing invoices', 'tips', 'freelance', '💸'),
  mk('My 4-week freelance roadmap for devs starting from zero', 'tips', 'freelance', '🗺️'),
  mk('How I turned one client into $60K in referrals', 'case-study', 'freelance', '🎁'),
  mk('Why your portfolio website is probably hurting your freelance business', 'engagement', 'freelance', '🚨'),
  mk('The onboarding flow that makes clients say "you\'re the most organized dev I\'ve worked with"', 'tips', 'freelance', '✅'),
  mk('How I write case studies that book calls (template included)', 'tips', 'freelance', '📊'),
  mk('Why I only work with clients who pay a deposit', 'thought-leadership', 'freelance', '💰'),
  mk('The freelance tax setup that saved me $8K last year', 'tips', 'freelance', '🧾'),
  mk('How to stop attracting cheap clients (mindset + tactical shift)', 'tips', 'freelance', '🎯'),
  mk('My exact email sequence for ghosted leads that books 20% of them', 'tips', 'freelance', '📧'),
  mk('Why niching down doubled my freelance revenue', 'story', 'freelance', '🎯', true),
  mk('The "project kickoff doc" I use with every client', 'tips', 'freelance', '🚀'),
  mk('5 red flags to reject a freelance client before you start', 'tips', 'freelance', '🚩'),
  mk('How I built a $200K/year freelance business in 18 months', 'story', 'freelance', '💵'),
  mk('The productized service that made my income predictable', 'thought-leadership', 'freelance', '📦'),
  mk('Why async communication beats daily standups for most freelance work', 'thought-leadership', 'freelance', '💬'),
  mk('The freelance calendar system that prevents burnout', 'tips', 'freelance', '📅'),
  mk('How I delegate 80% of non-coding work without a team', 'tips', 'freelance', '🤝'),
  mk('The "capacity planning" spreadsheet I wish I had 3 years ago', 'tips', 'freelance', '📊'),
  mk('Why most freelance devs stay broke (and how to avoid it)', 'engagement', 'freelance', '💸'),
  mk('My 3-tier pricing packages — and why they convert', 'tips', 'freelance', '💲'),
  mk('How I got 8 inbound leads last month without running ads', 'case-study', 'freelance', '📥'),
  mk('The freelance contract mistakes that cost me $15K', 'story', 'freelance', '😓'),
  mk('Why I charge for discovery calls now', 'thought-leadership', 'freelance', '💰', true),
  mk('The "Trojan horse" offer that gets me premium clients', 'tips', 'freelance', '🐴'),
  mk('How I turned a $500 project into a $20K contract', 'case-study', 'freelance', '📈'),
  mk('Why I keep a "never again" list of client types', 'thought-leadership', 'freelance', '🗒️'),
  mk('The referral framework that brings 30% of my new business', 'tips', 'freelance', '🔁'),
  mk('My step-by-step process for raising rates with existing clients', 'tips', 'freelance', '📊'),
  mk('How I write cold emails that get 15% reply rates', 'tips', 'freelance', '✉️'),
  mk('The freelance "runway" math every indie dev should do', 'thought-leadership', 'freelance', '🛬'),
  mk('Why I stopped offering free consultations', 'story', 'freelance', '🚫'),
  mk('The boring freelance habit that changed my entire income', 'story', 'freelance', '📔'),
  mk('How to productize your freelance service in 30 days', 'tips', 'freelance', '📦'),
  mk('My weekly freelance review ritual (10 minutes, massive impact)', 'tips', 'freelance', '🔍'),
  mk('Why I\'ll never work on a fixed-price project again (and what I do instead)', 'thought-leadership', 'freelance', '🎯'),
];

// =============================================
// Hot Takes (50)
// =============================================
const HOT_TAKES: TopicSuggestion[] = [
  mk('Vibe coding is dead. Here\'s what\'s replacing it in 2026.', 'engagement', 'hot-takes', '🔥', true),
  mk('AI won\'t replace devs. But devs who use AI will replace those who don\'t.', 'engagement', 'hot-takes', '🤖', true),
  mk('Why I prefer n8n over writing glue code — and when I don\'t', 'thought-leadership', 'hot-takes', '🧩'),
  mk('Cursor vs Copilot vs Claude Code — honest take after 6 months', 'thought-leadership', 'hot-takes', '⚡', true),
  mk('Stop fine-tuning. 99% of you don\'t need to.', 'engagement', 'hot-takes', '🛑'),
  mk('LangChain is holding back the AI engineering field', 'engagement', 'hot-takes', '🪦', true),
  mk('Your LLM doesn\'t need a vector database. Here\'s what it actually needs.', 'engagement', 'hot-takes', '🔍'),
  mk('Freelance > full-time for devs in 2026. Fight me.', 'engagement', 'hot-takes', '💼'),
  mk('Most "AI agents" are just workflows with extra steps', 'engagement', 'hot-takes', '🎭'),
  mk('Unpopular opinion: TypeScript isn\'t always worth it', 'engagement', 'hot-takes', '🔷'),
  mk('Portfolio sites are dead for freelance devs. Build in public instead.', 'engagement', 'hot-takes', '💀'),
  mk('Why 90% of AI startups will pivot to being tools, not products', 'thought-leadership', 'hot-takes', '🔧'),
  mk('GPT-4 is overkill for 70% of your use cases', 'engagement', 'hot-takes', '🔨'),
  mk('React was never meant for this. Here\'s why I use Solid now.', 'engagement', 'hot-takes', '⚛️'),
  mk('Unit tests are a waste of time for most freelance projects', 'engagement', 'hot-takes', '🧪'),
  mk('Hot take: your 500-page software architecture is slowing you down', 'engagement', 'hot-takes', '📚'),
  mk('Microservices were a mistake for your 5-person startup', 'engagement', 'hot-takes', '🔬'),
  mk('Stop writing custom auth. Clerk/Supabase/Auth.js handle 99% of cases.', 'engagement', 'hot-takes', '🔐'),
  mk('The "junior dev" era is ending. Here\'s what replaces it.', 'thought-leadership', 'hot-takes', '👨‍💻', true),
  mk('Why agencies are the dinosaurs of 2026', 'engagement', 'hot-takes', '🦖'),
  mk('Most devs won\'t survive the AI shift. Here\'s who will.', 'engagement', 'hot-takes', '📉'),
  mk('The death of the full-stack generalist has been greatly exaggerated', 'thought-leadership', 'hot-takes', '🧬'),
  mk('Why I don\'t trust devs who don\'t ship side projects', 'engagement', 'hot-takes', '🚀'),
  mk('If you can\'t explain your tech stack to a founder in 2 minutes, you\'re overengineered', 'engagement', 'hot-takes', '🗣️'),
  mk('College CS degrees are now a disadvantage for AI engineering roles', 'engagement', 'hot-takes', '🎓'),
  mk('Your SaaS is probably just a better-designed n8n workflow', 'engagement', 'hot-takes', '🧩', true),
  mk('The "learn AI or die" narrative is mostly hype — here\'s what to actually learn', 'thought-leadership', 'hot-takes', '📖'),
  mk('If you\'re not building with LLMs in 2026, you\'re a decade behind', 'engagement', 'hot-takes', '📅'),
  mk('Most dev bootcamps are scamming you in 2026', 'engagement', 'hot-takes', '🎣'),
  mk('I don\'t read documentation anymore. Here\'s what I do instead.', 'engagement', 'hot-takes', '📖'),
  mk('Why "best practices" are lying to you', 'engagement', 'hot-takes', '🚨'),
  mk('Engineering leaders: stop adding "AI" to your roadmap for investors', 'engagement', 'hot-takes', '💼'),
  mk('Docker for local dev is a solved problem — we just refuse to solve it', 'engagement', 'hot-takes', '🐳'),
  mk('Your startup doesn\'t need Kubernetes. It probably doesn\'t even need Docker.', 'engagement', 'hot-takes', '☸️'),
  mk('Code reviews are broken at most companies. Here\'s a better way.', 'thought-leadership', 'hot-takes', '👀'),
  mk('Why "move fast and break things" still works in 2026', 'thought-leadership', 'hot-takes', '💥'),
  mk('Remote-only is better than hybrid. Stop pretending otherwise.', 'engagement', 'hot-takes', '🏠'),
  mk('Your manager doesn\'t need your AI demo. They need your cost savings.', 'thought-leadership', 'hot-takes', '💰'),
  mk('Most ML engineers are just data plumbers in disguise', 'engagement', 'hot-takes', '🔧'),
  mk('I wouldn\'t hire a dev who doesn\'t use LLM tools daily', 'engagement', 'hot-takes', '🚫'),
  mk('No-code is eating full-stack development (and that\'s good for you)', 'thought-leadership', 'hot-takes', '🌱'),
  mk('If you\'re still writing CRUD apps manually in 2026, you\'re losing money', 'engagement', 'hot-takes', '💸'),
  mk('The "10x engineer" myth is now the "10x with AI" reality', 'thought-leadership', 'hot-takes', '⚡'),
  mk('Your framework doesn\'t matter. Your shipping cadence does.', 'engagement', 'hot-takes', '🚀'),
  mk('Stop learning frameworks. Learn principles.', 'engagement', 'hot-takes', '📚'),
  mk('Why I don\'t use GitHub Copilot anymore', 'story', 'hot-takes', '🤖'),
  mk('Medium articles are almost always wrong. Here\'s where I actually learn.', 'engagement', 'hot-takes', '📰'),
  mk('The "senior dev" title is meaningless in 2026. Here\'s what replaces it.', 'thought-leadership', 'hot-takes', '🏷️', true),
  mk('Soft skills > hard skills for freelance success. I\'ll die on this hill.', 'engagement', 'hot-takes', '💪'),
  mk('Why I\'d rather ship a B+ product than perfect an A+ one', 'thought-leadership', 'hot-takes', '🎯'),
];

// =============================================
// Case Studies (50)
// =============================================
const CASES: TopicSuggestion[] = [
  mk('How we turned a 40-hour manual process into a $0.30/task AI workflow', 'case-study', 'case-studies', '📈', true),
  mk('An agency drowning in onboarding. We built them an LLM assistant in 2 weeks.', 'case-study', 'case-studies', '🤝'),
  mk('We built an autonomous support agent that handles 60% of tickets', 'case-study', 'case-studies', '🎧', true),
  mk('From idea to funded MVP in 14 days — the exact stack we used', 'case-study', 'case-studies', '🚀'),
  mk('Client needed 10x lead qualification speed. We shipped it in a week.', 'case-study', 'case-studies', '⚡'),
  mk('How I rebuilt a client\'s broken Zapier empire with 3 n8n workflows', 'case-study', 'case-studies', '🔧'),
  mk('We cut a SaaS\'s AWS bill from $8K to $1.2K. Here\'s how.', 'case-study', 'case-studies', '💰', true),
  mk('The RAG system that made a legal firm 40% faster', 'case-study', 'case-studies', '⚖️'),
  mk('How we onboarded 2,000 users in 24 hours without touching the server', 'case-study', 'case-studies', '📊'),
  mk('Replacing a $200/mo SaaS with a 150-line Python script', 'case-study', 'case-studies', '🐍'),
  mk('A client spent $15K on agents that didn\'t work. We fixed it for $2K.', 'case-study', 'case-studies', '🔨'),
  mk('From 12 hours to 12 minutes: automating weekly client reports', 'case-study', 'case-studies', '📉'),
  mk('We built a Notion + GPT workflow that replaced 3 team members', 'case-study', 'case-studies', '🧠'),
  mk('The e-commerce checkout flow rebuild that increased conversions 23%', 'case-study', 'case-studies', '🛒'),
  mk('How we migrated a legacy PHP app to Next.js in 6 weeks (without downtime)', 'case-study', 'case-studies', '🔄'),
  mk('Shipping a voice AI onboarding flow for a fintech in 10 days', 'case-study', 'case-studies', '🎙️', true),
  mk('The newsletter automation that saved a creator 15 hours/week', 'case-study', 'case-studies', '📧'),
  mk('Built an AI analyst that reads Slack and writes weekly executive summaries', 'case-study', 'case-studies', '📝'),
  mk('We cut an agency\'s ad ops time by 80% with n8n + OpenAI', 'case-study', 'case-studies', '🎯'),
  mk('The data pipeline that gave a founder visibility he\'d never had before', 'case-study', 'case-studies', '📊'),
  mk('From "our website is broken" to 3x traffic in 30 days', 'case-study', 'case-studies', '🌐'),
  mk('The invoicing automation that fixed a client\'s cash flow', 'case-study', 'case-studies', '💵'),
  mk('How I built a custom CRM in 5 days with Supabase + n8n', 'case-study', 'case-studies', '📇'),
  mk('We replaced a 40-person data entry team with an AI pipeline', 'case-study', 'case-studies', '📋'),
  mk('The AI chatbot that doubled trial-to-paid conversions for a SaaS', 'case-study', 'case-studies', '💬'),
  mk('From zero code to production: a founder\'s MVP in 21 days', 'case-study', 'case-studies', '🎬'),
  mk('The migration from MongoDB to Postgres that saved 60% of query time', 'case-study', 'case-studies', '🗄️'),
  mk('How I rebuilt a client\'s broken auth system in a weekend', 'case-study', 'case-studies', '🔐'),
  mk('The Stripe integration that handled $1M in revenue in its first month', 'case-study', 'case-studies', '💳'),
  mk('We shipped a multi-tenant SaaS in 30 days. Here\'s the architecture.', 'case-study', 'case-studies', '🏢'),
  mk('The performance optimization that turned a 14s page load into 800ms', 'case-study', 'case-studies', '🏎️'),
  mk('Building an AI-powered recruiting pipeline that ranked 1,000 candidates/day', 'case-study', 'case-studies', '🎯'),
  mk('How I helped a course creator 10x their student engagement in 60 days', 'case-study', 'case-studies', '🎓'),
  mk('The content automation stack that published 50 blog posts in a week', 'case-study', 'case-studies', '📝'),
  mk('Turning a founder\'s scattered data into an actual dashboard', 'case-study', 'case-studies', '📊'),
  mk('How we used Whisper + GPT to transcribe 10 years of client calls', 'case-study', 'case-studies', '🎙️'),
  mk('The AI-powered QA system that caught 3 critical bugs before launch', 'case-study', 'case-studies', '🐛'),
  mk('Replacing Mailchimp with a custom n8n email system for a $2K/year saving', 'case-study', 'case-studies', '💸'),
  mk('How we built an internal search engine that made an agency 30% faster', 'case-study', 'case-studies', '🔎'),
  mk('The WhatsApp + GPT bot that handled 80% of customer queries', 'case-study', 'case-studies', '💬'),
  mk('From broken Shopify theme to fully custom storefront in 2 weeks', 'case-study', 'case-studies', '🛍️'),
  mk('The membership site we built that\'s now generating $14K MRR', 'case-study', 'case-studies', '👥'),
  mk('How we turned a founder\'s spreadsheet into a $8K project', 'case-study', 'case-studies', '📄'),
  mk('The recruitment AI that saved our client $40K/year in agency fees', 'case-study', 'case-studies', '🧑‍💼'),
  mk('Fixing a startup\'s embedding drift that was silently breaking RAG', 'case-study', 'case-studies', '🔬'),
  mk('How we instrumented a client\'s LLM product for 10x better observability', 'case-study', 'case-studies', '📡'),
  mk('The dashboard rebuild that got a startup their Series A data pitch together', 'case-study', 'case-studies', '🎯'),
  mk('A SaaS\'s dying retention — and the AI-powered fix that turned it around', 'case-study', 'case-studies', '📉'),
  mk('How I shipped a Claude-powered internal assistant in a Friday afternoon', 'case-study', 'case-studies', '⚡', true),
  mk('The payment reconciliation automation that saved 30 hours/month', 'case-study', 'case-studies', '💹'),
];

// =============================================
// Combine all + build trending list
// =============================================
const ALL = [...AI_AUTOMATION, ...LLMS, ...DEV, ...FREELANCE, ...HOT_TAKES, ...CASES];

// "Trending" is a virtual category — topics flagged with `trending: true` from any niche
export const TOPIC_SUGGESTIONS: TopicSuggestion[] = ALL;
